name: brain_dev_google_ads
description: "A Flutter project to manage Google Ads mobile."
version: 1.0.6+1
homepage: https://github.com/Grafritz/brain_dev_google_ads_plugin.git

#  dart pub publish --dry-run   #// Vérifier avant chaque nouvelle version
#  dart pub login
#  dart pub publish            # Publier la mise à jour

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8


  get: ^4.7.2
  shared_preferences: ^2.5.3

  google_mobile_ads: ^6.0.0

  # clear && flutter clean && rm -rf ~/.pub-cache/git && flutter pub get
  brain_dev_tools: ^1.0.6
    #path: /Users/jeanfritzduverseau/_Travaux/Projects/Flutter_Plugins/brain_dev_tools_plugin

  brain_dev_business: ^1.0.6
    #path: /Users/jeanfritzduverseau/_Travaux/Projects/Flutter_Plugins/brain_dev_business_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: net.braindev.brain_dev_google_ads
        pluginClass: BrainDevGoogleAdsPlugin
      ios:
        pluginClass: BrainDevGoogleAdsPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    - assets/img/pubs/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
